package Modelo;
// Generated 4/06/2016 10:51:19 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EsCandidato generated by hbm2java
 */
@Entity
@Table(name = "es_candidato", schema = "public"
)
public class EsCandidato implements java.io.Serializable {

    private EsCandidatoId id;
    private Publicacion publicacion;
    private Usuario usuario;

    public EsCandidato() {
    }

    public EsCandidato(EsCandidatoId id) {
        this.id = id;
    }

    public EsCandidato(EsCandidatoId id, Publicacion publicacion, Usuario usuario) {
        this.id = id;
        this.publicacion = publicacion;
        this.usuario = usuario;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "idCandidato", column = @Column(name = "id_candidato")),
        @AttributeOverride(name = "idPublicacion", column = @Column(name = "id_publicacion"))})
    public EsCandidatoId getId() {
        return this.id;
    }

    public void setId(EsCandidatoId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_publicacion", insertable = false, updatable = false)
    public Publicacion getPublicacion() {
        return this.publicacion;
    }

    public void setPublicacion(Publicacion publicacion) {
        this.publicacion = publicacion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_candidato", insertable = false, updatable = false)
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

}
