package Modelo;
// Generated 4/06/2016 10:51:19 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EsCandidatoId generated by hbm2java
 */
@Embeddable
public class EsCandidatoId  implements java.io.Serializable {


     private Integer idCandidato;
     private Integer idPublicacion;

    public EsCandidatoId() {
    }

    public EsCandidatoId(Integer idCandidato, Integer idPublicacion) {
       this.idCandidato = idCandidato;
       this.idPublicacion = idPublicacion;
    }
   


    @Column(name="id_candidato")
    public Integer getIdCandidato() {
        return this.idCandidato;
    }
    
    public void setIdCandidato(Integer idCandidato) {
        this.idCandidato = idCandidato;
    }


    @Column(name="id_publicacion")
    public Integer getIdPublicacion() {
        return this.idPublicacion;
    }
    
    public void setIdPublicacion(Integer idPublicacion) {
        this.idPublicacion = idPublicacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EsCandidatoId) ) return false;
		 EsCandidatoId castOther = ( EsCandidatoId ) other; 
         
		 return ( (this.getIdCandidato()==castOther.getIdCandidato()) || ( this.getIdCandidato()!=null && castOther.getIdCandidato()!=null && this.getIdCandidato().equals(castOther.getIdCandidato()) ) )
 && ( (this.getIdPublicacion()==castOther.getIdPublicacion()) || ( this.getIdPublicacion()!=null && castOther.getIdPublicacion()!=null && this.getIdPublicacion().equals(castOther.getIdPublicacion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdCandidato() == null ? 0 : this.getIdCandidato().hashCode() );
         result = 37 * result + ( getIdPublicacion() == null ? 0 : this.getIdPublicacion().hashCode() );
         return result;
   }   


}


