package Modelo;
// Generated 4/06/2016 10:51:19 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Publicacion generated by hbm2java
 */
@Entity
@Table(name = "publicacion", schema = "public"
)
public class Publicacion implements java.io.Serializable {

    private int idPublicacion;
    private Usuario usuarioByIdDueno;
    private Usuario usuarioByElegido;
    private String resena;
    private String titulo;
    private String autor;
    private String edicion;
    private String isbn;
    private Integer anio;
    private Integer evaluacionDelContenido;
    private String foto;
    private String editorial;
    private Integer evaluacionDeRedaccion;
    private boolean finalizado;
    private Date fecha;
    private String lugarDeIntercambio;
    private Set esCandidatos = new HashSet(0);

    public Publicacion() {
    }

    public Publicacion(int idPublicacion, String titulo, String autor, boolean finalizado, Date fecha) {
        this.idPublicacion = idPublicacion;
        this.titulo = titulo;
        this.autor = autor;
        this.finalizado = finalizado;
        this.fecha = fecha;
    }

    public Publicacion(int idPublicacion, Usuario usuarioByIdDueno, Usuario usuarioByElegido, String resena, String titulo, String autor, String edicion, String isbn, Integer anio, Integer evaluacionDelContenido, String foto, String editorial, Integer evaluacionDeRedaccion, boolean finalizado, Date fecha, String lugarDeIntercambio, Set esCandidatos) {
        this.idPublicacion = idPublicacion;
        this.usuarioByIdDueno = usuarioByIdDueno;
        this.usuarioByElegido = usuarioByElegido;
        this.resena = resena;
        this.titulo = titulo;
        this.autor = autor;
        this.edicion = edicion;
        this.isbn = isbn;
        this.anio = anio;
        this.evaluacionDelContenido = evaluacionDelContenido;
        this.foto = foto;
        this.editorial = editorial;
        this.evaluacionDeRedaccion = evaluacionDeRedaccion;
        this.finalizado = finalizado;
        this.fecha = fecha;
        this.lugarDeIntercambio = lugarDeIntercambio;
        this.esCandidatos = esCandidatos;
    }

    @Id

    @Column(name = "id_publicacion", unique = true, nullable = false)
    public int getIdPublicacion() {
        return this.idPublicacion;
    }

    public void setIdPublicacion(int idPublicacion) {
        this.idPublicacion = idPublicacion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_dueno")
    public Usuario getUsuarioByIdDueno() {
        return this.usuarioByIdDueno;
    }

    public void setUsuarioByIdDueno(Usuario usuarioByIdDueno) {
        this.usuarioByIdDueno = usuarioByIdDueno;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "elegido")
    public Usuario getUsuarioByElegido() {
        return this.usuarioByElegido;
    }

    public void setUsuarioByElegido(Usuario usuarioByElegido) {
        this.usuarioByElegido = usuarioByElegido;
    }

    @Column(name = "resena")
    public String getResena() {
        return this.resena;
    }

    public void setResena(String resena) {
        this.resena = resena;
    }

    @Column(name = "titulo", nullable = false)
    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    @Column(name = "autor", nullable = false)
    public String getAutor() {
        return this.autor;
    }

    public void setAutor(String autor) {
        this.autor = autor;
    }

    @Column(name = "edicion")
    public String getEdicion() {
        return this.edicion;
    }

    public void setEdicion(String edicion) {
        this.edicion = edicion;
    }

    @Column(name = "isbn")
    public String getIsbn() {
        return this.isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    @Column(name = "anio")
    public Integer getAnio() {
        return this.anio;
    }

    public void setAnio(Integer anio) {
        this.anio = anio;
    }

    @Column(name = "evaluacion_del_contenido")
    public Integer getEvaluacionDelContenido() {
        return this.evaluacionDelContenido;
    }

    public void setEvaluacionDelContenido(Integer evaluacionDelContenido) {
        this.evaluacionDelContenido = evaluacionDelContenido;
    }

    @Column(name = "foto")
    public String getFoto() {
        return this.foto;
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }

    @Column(name = "editorial")
    public String getEditorial() {
        return this.editorial;
    }

    public void setEditorial(String editorial) {
        this.editorial = editorial;
    }

    @Column(name = "evaluacion_de_redaccion")
    public Integer getEvaluacionDeRedaccion() {
        return this.evaluacionDeRedaccion;
    }

    public void setEvaluacionDeRedaccion(Integer evaluacionDeRedaccion) {
        this.evaluacionDeRedaccion = evaluacionDeRedaccion;
    }

    @Column(name = "finalizado", nullable = false)
    public boolean isFinalizado() {
        return this.finalizado;
    }

    public void setFinalizado(boolean finalizado) {
        this.finalizado = finalizado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha", nullable = false, length = 13)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Column(name = "lugar_de_intercambio")
    public String getLugarDeIntercambio() {
        return this.lugarDeIntercambio;
    }

    public void setLugarDeIntercambio(String lugarDeIntercambio) {
        this.lugarDeIntercambio = lugarDeIntercambio;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "publicacion")
    public Set getEsCandidatos() {
        return this.esCandidatos;
    }

    public void setEsCandidatos(Set esCandidatos) {
        this.esCandidatos = esCandidatos;
    }

    /* Regresa la ruta absoluta a la foto del libro */
    public String getRutaFoto() {
        if (this.foto == null || this.foto.equals("")) {
            return "";
        }
        return System.getProperty("user.dir") + "/imagenes/" + this.foto;
    }

}
