package Modelo;
// Generated 11/05/2016 04:32:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="correo") 
)
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String nombre;
     private String contrasena;
     private String correo;
     private String telefono;
     private Set libros = new HashSet(0);
     private Set publicacions = new HashSet(0);
     private Set esCandidatos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, String nombre, String contrasena, String correo) {
        this.idUsuario = idUsuario;
        this.nombre = nombre;
        this.contrasena = contrasena;
        this.correo = correo;
    }
    public Usuario(int idUsuario, String nombre, String contrasena, String correo, String telefono, Set libros, Set publicacions, Set esCandidatos) {
       this.idUsuario = idUsuario;
       this.nombre = nombre;
       this.contrasena = contrasena;
       this.correo = correo;
       this.telefono = telefono;
       this.libros = libros;
       this.publicacions = publicacions;
       this.esCandidatos = esCandidatos;
    }
   
     @Id 

    
    @Column(name="id_usuario", unique=true, nullable=false)
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="nombre", nullable=false)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="contrasena", nullable=false)
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    
    @Column(name="correo", unique=true, nullable=false)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="telefono", length=15)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getLibros() {
        return this.libros;
    }
    
    public void setLibros(Set libros) {
        this.libros = libros;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getPublicacions() {
        return this.publicacions;
    }
    
    public void setPublicacions(Set publicacions) {
        this.publicacions = publicacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getEsCandidatos() {
        return this.esCandidatos;
    }
    
    public void setEsCandidatos(Set esCandidatos) {
        this.esCandidatos = esCandidatos;
    }




}


